name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push_docker_image:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push the Docker image
      env:
        DOCKER_IMAGE_TAG: latest
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:${DOCKER_IMAGE_TAG} .
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${DOCKER_IMAGE_TAG}
